'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CPU_Scheduling_Algorithm.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artificial_intelligence__800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artificial intelligence (800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artificial_intelligence__800_x_450_px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artificial intelligence (800 x 450 px)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artificial_intelligence_1___800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artificial intelligence 1. (800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property artificial_intelligence_1_1__800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("artificial intelligence 1.1 (800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B_800_x_450_px___40_x_40_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B(800 x 450 px) (40 x 40 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B_800_x_450_px___40_x_40_px___176_x_82_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B(800 x 450 px) (40 x 40 px) (176 x 82 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B_800_x_450_px___40_x_40_px___176_x_82_px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B(800 x 450 px) (40 x 40 px) (176 x 82 px)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B_800_x_450_px___40_x_40_px___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B(800 x 450 px) (40 x 40 px) (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B_800_x_450_px___40_x_40_px___3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B(800 x 450 px) (40 x 40 px) (3)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cute_Wood_Game_Button_Twitch_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cute Wood Game Button Twitch Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cute_Wood_Game_Button_Twitch_Panel__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cute Wood Game Button Twitch Panel (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cute_Wood_snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cute Wood snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cute_Wood_snow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cute Wood snow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EX_800_x_450_px___40_x_40_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EX(800 x 450 px) (40 x 40 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EXx_800_x_450_px___40_x_40_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXx(800 x 450 px) (40 x 40 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFS__228_x_81_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFS (228 x 81 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fCFS__228_x_81_px___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fCFS (228 x 81 px) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fCFS__228_x_81_px___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fCFS (228 x 81 px) (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fCFS__228_x_81_px___2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fCFS (228 x 81 px) (2)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFS1__800_x_600_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFS1 (800 x 600 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFS1__800_x_600_px___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFS1 (800 x 600 px) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFS1__800_x_600_px___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFS1 (800 x 600 px) (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFS1_1_800_x_600_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFS1.1(800 x 600 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFSscheduling1_800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFSscheduling1.800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FCFSscheduling1_800_x_450_px___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FCFSscheduling1.800 x 450 px) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lagoon_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lagoon.1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lagoon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lagoon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading_800_x_450_px___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading.800 x 450 px) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lOADING_800_x_450_px_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lOADING(800 x 450 px)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loading1_800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loading1.800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu(800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menu_800_x_450_px___1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu(800 x 450 px) (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menu_800_x_450_px___2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu(800 x 450 px) (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu1_800_x_450_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu1.800 x 450 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PriorityUI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PriorityUI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PriorityUI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PriorityUI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PriorityUIi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PriorityUIi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property process__400_x_300_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("process (400 x 300 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Restart_800_x_450_px___40_x_40_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Restart(800 x 450 px) (40 x 40 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RoundrobinUI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RoundrobinUI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RoundRobinUIi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RoundRobinUIi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SJf__228_x_81_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SJf (228 x 81 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SJFfinalUI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SJFfinalUI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled__400_x_300_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled (400 x 300 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property X_800_x_450_px___40_x_40_px_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X(800 x 450 px) (40 x 40 px)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
